services:
  node_cli:
    image: zcodeapp/node_backend
    build:
      context: ${PWD}
      dockerfile: docker/node/Dockerfile
    volumes:
      - ${PWD}:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
      - DOCKERHUB_ACCESS_TOKEN=${DOCKERHUB_ACCESS_TOKEN}

  nest_dev:
    image: zcodeapp/node_backend
    build:
      context: ${PWD}
      dockerfile: docker/node/Dockerfile
    depends_on:
      - node_cli
    entrypoint: bin/node/nest
    volumes:
      - ${PWD}:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4000:4000
    environment:
      - PORT=4000

  nest_debug:
    image: zcodeapp/node_backend
    build:
      context: ${PWD}
      dockerfile: docker/node/Dockerfile
    depends_on:
      - node_cli
    entrypoint: bin/node/nest_debug
    volumes:
      - ${PWD}:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      - PORT=4000

  nest_test:
    image: zcodeapp/node_backend
    build:
      context: ${PWD}
      dockerfile: docker/node/Dockerfile
    depends_on:
      - node_cli
    entrypoint: /bin/bash
    command: ''
    volumes:
      - ${PWD}:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=4000
