name: ZCode App
on:
  push:
    branches:
      - "main"
jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    environment: development
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: "bin/ci/install -e development"
      - name: Cache
        id: cache-install
        uses: actions/cache/save@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: List content
        run: ls -la . && echo $PWD
  test_unit:
    name: Test Unit
    runs-on: ubuntu-latest
    needs:
    - install
    environment: development
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Restore Cache
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: List content
        run: ls -la . && echo $PWD
      - name: Test
        run: "bin/ci/test_unit -e development"
  test_e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    needs:
    - install
    - test_unit
    environment: development
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Restore Cache
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: Test
        run: "bin/ci/test_e2e -e development"
  test_container:
    name: Test Container
    runs-on: ubuntu-latest
    needs:
    - install
    - test_unit
    environment: development
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Restore Cache
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: Image
        run: "bin/ci/image -e development -d zcodeapp/ide-server"
      - name: Start ZCode APP IDE Server
        uses: zcodeapp/ide-server-github-action@1.0.1
      - name: Test Image
        run: "bin/ci/test_container -e development"
  build:
    name: Build container for official image on Docker
    runs-on: ubuntu-latest
    needs:
    - test_unit
    - test_e2e
    - test_container
    environment: production
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: production
      DOCKERHUB_USERNAME: '${{ secrets.DOCKERHUB_USERNAME }}'
      DOCKERHUB_ACCESS_TOKEN: '${{ secrets.DOCKERHUB_ACCESS_TOKEN }}'
    steps:
      - name: Restore Cache
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: Push
        run: "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME DOCKERHUB_ACCESS_TOKEN=$DOCKERHUB_ACCESS_TOKEN bin/ci/push -e production"
