name: ZCode App
on:
  push:
    branches:
      - "main"
jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    environment: development
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: "bin/ci/install -e development"
      - name: Build
        run: "bin/ci/build -e development"
      - name: Cache
        id: cache-install
        uses: actions/cache/save@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: List content
        run: ls -la . && echo $PWD

  test_unit:
    name: Test Unit
    runs-on: ubuntu-latest
    needs:
    - install
    environment: development
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Restore Install
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: List content
        run: ls -la . && echo $PWD
      - name: Test
        run: "bin/ci/test_unit -e development"

  test_e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    needs:
    - install
    environment: development
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Restore Install
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: Test
        run: "bin/ci/test_e2e -e development"

  image:
    name: Create image
    runs-on: ubuntu-latest
    needs:
    - install
    environment: development
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Restore Install
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: Create Image
        run: "bin/ci/image -e development -d zcodeapp/ide-server"
      - name: Save Image
        run: mkdir images && docker image save --output images/zcodeapp-ide-server.tar zcodeapp/ide-server
      - name: Cache Image
        id: cache-image
        uses: actions/cache/save@v3
        with:
          path: images
          key: ${{ runner.os }}-image-${{ hashFiles('package.json') }}

  test_container:
    name: Test Container
    runs-on: ubuntu-latest
    needs:
    - image
    environment: development
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Restore Install
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: Restore Image
        id: cache-image
        uses: actions/cache/restore@v3
        with:
          path: images
          key: ${{ runner.os }}-image-${{ hashFiles('package.json') }}
      - name: Import Image
        run: docker image load -i images/zcodeapp-ide-server.tar
      - name: Image Tag
        run: docker tag zcodeapp/ide-server:latest zcodeapp/ide-server:test_version
      - name: Start ZCode APP IDE Server
        uses: zcodeapp/ide-server-github-action@1.0.2
        with:
          ide-server-version: test_version
      - name: Test Image
        run: "bin/ci/test_container -e development"

  push:
    name: Build container for official image on Docker
    runs-on: ubuntu-latest
    needs:
    - install
    - test_unit
    - test_e2e
    - image
    - test_container
    environment: production
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: production
      DOCKERHUB_USERNAME: '${{ secrets.DOCKERHUB_USERNAME }}'
      DOCKERHUB_ACCESS_TOKEN: '${{ secrets.DOCKERHUB_ACCESS_TOKEN }}'
    steps:
      - name: Restore Install
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ hashFiles('package.json') }}
      - name: Push
        run: "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME DOCKERHUB_ACCESS_TOKEN=$DOCKERHUB_ACCESS_TOKEN bin/ci/push -e production"
