name: ZCode App
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build ZCodeApp to Docker
    runs-on: ubuntu-latest
    container:
      image: zcodeapp/node_backend
      options: --user root
      env:
        NODE_ENV: development
        DOCKERHUB_USERNAME: zcodeapp
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME DOCKERHUB_ACCESS_TOKEN=$DOCKERHUB_ACCESS_TOKEN bin/ci/build"
