name: ZCode App
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Install, test and build container for official image on Docker
    runs-on: ubuntu-latest
    environment: production
    container:
      image: zcodeapp/node_backend
      options: --user root
    env:
      NODE_ENV: production
      DOCKERHUB_USERNAME: '${{ secrets.DOCKERHUB_USERNAME }}'
      DOCKERHUB_ACCESS_TOKEN: '${{ secrets.DOCKERHUB_ACCESS_TOKEN }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Node packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            /var/www/node_modules
      - name: Install
        run: "bin/ci/install"
      - name: Test
        run: "bin/ci/test"
      - name: Build
        run: "bin/ci/build"
      - name: Push
        run: "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME DOCKERHUB_ACCESS_TOKEN=$DOCKERHUB_ACCESS_TOKEN bin/ci/push"
